#!/bin/bash
echo "🔑 Update these GitHub repository secrets:"
echo "=========================================="
echo ""
echo "Go to: https://github.com/thomasjamais/financial-helper/settings/secrets/actions"
echo ""
echo "Update these secrets:"
echo "PROGRAMMER_TASK_DEFINITION=financial-helper-programmer-agent:15"
echo "PRODUCT_TASK_DEFINITION=financial-helper-product-agent:5"
echo ""
echo "Other secrets (should already be set):"
echo "AWS_ACCESS_KEY_ID=[YOUR_ACCESS_KEY_ID]"
echo "AWS_SECRET_ACCESS_KEY=[YOUR_SECRET_ACCESS_KEY]"
echo "AWS_REGION=eu-west-3"
echo "ECS_CLUSTER=financial-helper-cluster"
echo "SUBNET_IDS=subnet-0480c0bbbb272c7f3,subnet-09e259a38907a945d"
echo "SECURITY_GROUP_IDS=sg-055ceedf4e4a2781d"
echo ""
echo "After updating secrets, test by:"
echo "1. Go to https://github.com/thomasjamais/financial-helper/issues/2"
echo "2. Remove 'ai' label"
echo "3. Add 'ai' label back"
echo "4. Watch logs: aws logs tail '/ecs/financial-helper-agent' --region eu-west-3 --follow"
