version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ctd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: ctd-redis
    restart: unless-stopped
    ports: ["6379:6379"]
volumes:
  pgdata: {}
