name: AI Fix Agent

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ai-fix-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  fix-agent:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/ai:fix')
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get PR details
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });
            
            core.setOutput('pr_number', pr.number);
            core.setOutput('head_ref', pr.head.ref);
            core.setOutput('head_sha', pr.head.sha);

      - name: Run Fix Agent
        uses: muya/amazon-ecs-run-task@v1
        with:
          task-definition: ${{ secrets.PROGRAMMER_TASK_DEFINITION }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          subnets: ${{ secrets.SUBNET_IDS }}
          security-groups: ${{ secrets.SECURITY_GROUP_IDS }}
          assign-public-ip: ENABLED
          wait-for-finish: true
          wait-for-minutes: 10
          count: 1
          launch-type: FARGATE