name: AI Product Agent

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ai-product-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  product-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Product Agent
        uses: aws-actions/amazon-ecs-run-task@v2
        with:
          task-definition: ${{ secrets.PRODUCT_TASK_DEFINITION }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          subnet-ids: ${{ secrets.SUBNET_IDS }}
          security-group-ids: ${{ secrets.SECURITY_GROUP_IDS }}
          assign-public-ip: ENABLED
          wait-for-finish: true
          overrides: |
            {
              "containerOverrides": [
                {
                  "name": "product-agent",
                  "environment": [
                    {
                      "name": "GITHUB_TOKEN",
                      "value": "${{ secrets.GITHUB_TOKEN }}"
                    },
                    {
                      "name": "GH_OWNER",
                      "value": "${{ github.repository_owner }}"
                    },
                    {
                      "name": "GH_REPO",
                      "value": "${{ github.event.repository.name }}"
                    },
                    {
                      "name": "PR_NUMBER",
                      "value": "${{ github.event.pull_request.number }}"
                    },
                    {
                      "name": "POLICY_PATH",
                      "value": "/workspace/policy.yaml"
                    }
                  ]
                }
              ]
            }