name: AI Product Agent

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ai-product-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  product-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Product Agent
        uses: muya/amazon-ecs-run-task@v1
        with:
          task-definition: ${{ secrets.PRODUCT_TASK_DEFINITION }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          subnet-ids: ${{ secrets.SUBNET_IDS }}
          security-group-ids: ${{ secrets.SECURITY_GROUP_IDS }}
          assign-public-ip: ENABLED
          wait-for-finish: true
          wait-for-minutes: 10
          environment-variables: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            GH_OWNER=${{ github.repository_owner }}
            GH_REPO=${{ github.event.repository.name }}
            PR_NUMBER=${{ github.event.pull_request.number }}
            POLICY_PATH=/workspace/policy.yaml