name: Test Plan Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  test-plan-trigger:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'plan')) || 
      (github.event.action == 'reopened' && contains(github.event.issue.labels.*.name, 'plan')) || 
      (github.event.action == 'labeled' && github.event.label.name == 'plan')
    
    steps:
      - name: Debug Context
        run: |
          echo "✅ Plan workflow triggered!"
          echo "Action: ${{ github.event.action }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
          echo "Label names: ${{ github.event.issue.labels.*.name }}"
          echo "Contains plan: ${{ contains(github.event.issue.labels.*.name, 'plan') }}"
          if [ "${{ github.event.action }}" = "labeled" ]; then
            echo "Label added: ${{ github.event.label.name }}"
          fi
      
      - name: Success
        run: echo "🎉 Plan workflow is working correctly!"

  test-programmer-trigger:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'opened' || 
       github.event.action == 'reopened' || 
       (github.event.action == 'labeled' && github.event.label.name == 'ai')) &&
      !contains(github.event.issue.labels.*.name, 'plan')
    
    steps:
      - name: Debug Context
        run: |
          echo "✅ Programmer workflow triggered!"
          echo "Action: ${{ github.event.action }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
          echo "Contains plan: ${{ contains(github.event.issue.labels.*.name, 'plan') }}"
      
      - name: Success
        run: echo "🎉 Programmer workflow is working correctly!"

  test-skip:
    runs-on: ubuntu-latest
    if: |
      !((github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'plan')) || 
        (github.event.action == 'reopened' && contains(github.event.issue.labels.*.name, 'plan')) || 
        (github.event.action == 'labeled' && github.event.label.name == 'plan')) &&
      !((github.event.action == 'opened' || 
         github.event.action == 'reopened' || 
         (github.event.action == 'labeled' && github.event.label.name == 'ai')) &&
        !contains(github.event.issue.labels.*.name, 'plan'))
    
    steps:
      - name: Debug Context
        run: |
          echo "⏭️  Workflow skipped (as expected)"
          echo "Action: ${{ github.event.action }}"
          echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
          echo "Label names: ${{ github.event.issue.labels.*.name }}"
